project:
  type: website

website:
  title: "Bernd Doser"
  favicon: images/favicon.png
  navbar:
    right:
      - icon: github
        href: https://github.com/bernddoser
      - icon: mastodon
        href: https://mastodon.world/@braintwister
      - icon: twitter
        href: https://twitter.com/BerndDoser
      - icon: linkedin
        href: https://www.linkedin.com/in/bernddoser

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    colorlinks: true
    toc: false
